#!/bin/bash

source ../config

if [ "$BUILD_MODE" == "offline" ]; then
  echo "offline build"
else
  npm install
fi

# Compile LiveScript sources using the local LiveScript install
./node_modules/LiveScript/bin/lsc -c *.ls
