// Generated by LiveScript 1.2.0
var shoe, through, divs;
window.VIS = {};
window.VIS.main = (shoe = require('shoe'), through = require('through'), divs = {}, function(){
  var x$;
  x$ = shoe('/racedata');
  x$.pipe(through(function(data){
    var msg, div;
    console.dir(data);
    msg = JSON.parse(data);
    if (msg.msgType in divs) {
      return divs[msg.msgType].innerHTML = data;
    } else {
      document.body.appendChild(
      document.createTextNode(msg.msgType + ': '));
      div = divs[msg.msgType] = document.createElement('div');
      div.innerHTML = data;
      return document.body.appendChild(div);
    }
  }));
  return x$;
});