// Generated by LiveScript 1.2.0
var VIS;
VIS = {};
VIS.main = function(){
  var shoe, through, divs;
  shoe = require('shoe');
  through = require('through');
  divs = {};
  return function(){
    var stream;
    stream = shoe('/racedata');
    return stream.pipe(
    through(function(data){
      var msg, div;
      msg = JSON.parse(data);
      if (msg.msgType in divs) {
        divs[msg.msgType].innerHTML = data;
      } else {
        document.body.appendChild(
        document.createTextNode(msg.msgType + ': '));
        div = divs[msg.msgType] = document.createElement('div');
        div.innerHTML = data;
        document.body.appendChild(div);
      }
    }));
  };
}();